### ISSUE TITLE
类似这种网站真的是越来越多了

### ISSUE THREAD

**Issue by richshaw2015** [shidenggui/bloghub#1]
[己思](https://ohmyrss.com/) 、[寻我](https://seekbetter.me/)、[IT瘾](http://itindex.net/)、[ReadingTrip](http://readingtrip.com/)、[Feeds.Pub](https://feeds.pub/)。。。

**Comment by shidenggui** [comment]
用户有更多选择是好事。每个产品都有不同的差异。
