### ISSUE TITLE
【订阅无法使用】blog SSR 订阅无法使用

### ISSUE THREAD

**Issue by DanielZhui** [shidenggui/bloghub#156]
![image](https://user-images.githubusercontent.com/44571398/128454076-ae8003c1-4b33-457f-9cb2-f19c76b84fa7.png)
![image](https://user-images.githubusercontent.com/44571398/128454114-c23957e7-3585-4e58-9e55-33cedc9f5d73.png)

**Comment by shidenggui** [comment]
已经修复
