### ISSUE TITLE
沐风的博客

### ISSUE THREAD

**Issue by mufengcoding** [shidenggui/bloghub#19]
Introduction: 沐风的博客
Address: https://blog.mufengs.com/
RSS feed: https://blog.mufengs.com/rss.xml
tags: 有趣; 博文

**Comment by shidenggui** [comment]
好像你的 rss 最近几篇文章都没有 summary，看以前的文章是有的，不知道为什么后面没了？
如果以后都不在提供的话，暂时会从 bloghub.fun 移除

**Comment by mufengcoding** [comment]
好的，之前写的时候summary有些没写，以后 每个文章都会加上


开 2020年3月13日 在 下午8:19:48, shidenggui (notifications@github.com) 写到:

 bloghub.fun
