### ISSUE TITLE
日常呗

### ISSUE THREAD

**Issue by richangbe** [shidenggui/bloghub#32]
Introduction: 我们每天所度过的「日常」呗，说不定实际上就是一个个奇迹的连续而成的呢！
Address: https://richang.be/
RSS feed: https://feeds.feedburner.com/richangbe
tags: 日常; 生活; 日本

**Comment by shidenggui** [comment]
bloghub.fun 的服务器在国内，https://feeds.feedburner.com/richangbe 这个地址无法访问。
