### ISSUE TITLE
樵夫的小站 geofftools.cn

### ISSUE THREAD

**Issue by geeeeoff** [shidenggui/bloghub#41]
Introduction: 樵夫的小站
Address: https://geofftools.cn
RSS feed: https://geofftools.cn/blog/atom.xml
tags: 编程；Swift；Python

**Comment by shidenggui** [comment]
之前已经收录了，但是没处理好博客链接里面带 `/` 所以没正常显示，现在已经有了 `https://bloghub.fun/blogs/geofftools.cn/blog`
